### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by soulshake** [convox/site#333]
_From @nzoschke on October 17, 2016 23:0_

@jtvhk offered great feedback: the 'balancer' section should cover SSL. The simplest implementation would be to use a manifest like:

``` yaml
version: '2'
services:
  web:
    build: .
    command: ["node", "web.js"]
    labels:
     - convox.port.443.protocol=https
    ports:
     - 80:8000
     - 443:8000
  worker:
    build: .
    command: ["node", "worker.js"]
    environment:
     - GITHUB_API_TOKEN
```

_Copied from original issue: convox/guide#6_
